Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: title
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: queryUserPosts
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: title
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TableName: RelayAppSyncDynamoDBTable

Outputs:
  DynamoDBTableName:
    Value: !Ref DynamoDBTable
    Export:
      Name: !Join [':', [!Ref 'AWS::StackName', DynamoDBTableName]]

  DynamoDBTableRegion:
    Value: !Ref AWS::Region
    Export:
      Name: !Join [':', [!Ref 'AWS::StackName', DynamoDBTableRegion]]

  DynamoDBTableArn:
    Value: !GetAtt DynamoDBTable.Arn
    Export:
      Name: !Join [':', [!Ref 'AWS::StackName', DynamoDBTableArn]]
